name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd hse-python-project
            git pull
            docker compose down -v
            docker image rm hse-python-project-streamlit
            docker image rm hse-python-project-web
            docker compose pull --quiet
            docker compose up --detach